export const STRING_CONSTANT = Object.freeze({
    SINGLE_TYPE: "single",
    MULTIPLE_TYPE: "multiple",
    INSIDE: "INSIDE",
    OUTSIDE: "OUTSIDE",
    SUCCESS: "success",
    INPROGRESS: "IN_PROGRESS",
    FAILURE: "FAILURE",
    ALL: "all",
    QUERY: "query",
    PARAMS: "params",
    TRUE: "true",
    EMPTY: "",
    OFFSITE: "offsite",
    PRESENT: "present",
    NA: "N/A",
    APPROVED: "Approved",
    REJECTED: "Rejected",
    APPROVE: "APPROVE",
    REJECT: "REJECT"
});
